# This file is part of Werkstatt.
#
# Werkstatt is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Werkstatt is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Werkstatt. If not, see <https://www.gnu.org/licenses/>.

##
# Ansible playbook that runs all the subsidiary playbooks (except for
# fabrik.playbook.yml) in the correct sequence.
#
# This playbook should only be run if the target distribution (Fabrik) has
# already been prepared with the manual steps described in CONTRIBUTING.md and
# with the fabrik.playbook.yml playbook.
#
# @see        {@link https://github.com/geoffreyvanwyk/werkstatt}
# @author     Geoffrey Bernardo van Wyk <geoffrey@vanwyk.biz>
# @copyright  2024 Geoffrey Bernardo van Wyk {@link https://geoffreyvanwyk.dev}
# @license    {@link http://www.gnu.org/copyleft/gpl.html} GNU GPL v3 or later
##
---
- name: Main
  hosts: all

  tasks:
    - name: Ensure packages are up-to-date
      become: yes
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ 60 * 60 * 24 * 7 }}" # 7 days in seconds
        upgrade: true

    ##
    # XDG Base Directories is a specification from the Free Desktop community of
    # projects.
    #
    # @see  {@link https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html}
    ##
    - name: Create XDG directories
      block:
        - name: Create $XDG_BIN_HOME
          ansible.builtin.file:
            path: "{{ werkstatt_xdg_bin_home }}"
            state: directory
            mode: u=rwX,go=rX

        - name: Create $XDG_CACHE_HOME
          ansible.builtin.file:
            path: "{{ werkstatt_xdg_cache_home }}"
            state: directory
            mode: u=rwX,go=rX

        - name: Create $XDG_CONFIG_HOME
          ansible.builtin.file:
            path: "{{ werkstatt_xdg_config_home }}"
            state: directory
            mode: u=rwX,go=rX

        - name: Create $XDG_DATA_HOME
          ansible.builtin.file:
            path: "{{ werkstatt_xdg_data_home }}"
            state: directory
            mode: u=rwX,go=rX

        - name: Create $XDG_STATE_HOME
          ansible.builtin.file:
            path: "{{ werkstatt_xdg_state_home }}"
            state: directory
            mode: u=rwX,go=rX

    - name: Create Werkstatt project data directory
      ansible.builtin.file:
        path: "{{ werkstatt_data_dir }}"
        state: directory
        mode: u=rwX,go=rX

- name: BASH - Bourne Again Shell
  ansible.builtin.import_playbook: ./shell_bash.playbook.yml

- name: Starship - minimal, blazingly fast, infinitely customizable shell prompt
  ansible.builtin.import_playbook: ./shellprompt_starship.playbook.yml

- name: Python Programming Language
  ansible.builtin.import_playbook: ./lang_python.playbook.yml

- name: Ruby Programming Language
  ansible.builtin.import_playbook: ./lang_ruby.playbook.yml

- name: JavaScript Programming Language
  ansible.builtin.import_playbook: ./lang_javascript.playbook.yml

- name: PHP Programming Language
  ansible.builtin.import_playbook: ./lang_php.playbook.yml

- name: Rust Programming Language
  ansible.builtin.import_playbook: ./lang_rust.playbook.yml

- name: Go Programming Language
  ansible.builtin.import_playbook: ./lang_go.playbook.yml

- name: Git for Version Control of Source Code
  ansible.builtin.import_playbook: ./versioncontrol_git.playbook.yml

- name: Tmux Multiplexer
  ansible.builtin.import_playbook: ./multiplexer_tmux.playbook.yml

- name: Utility Programmes
  ansible.builtin.import_playbook: ./utils.playbook.yml

- name: Docker for Containerization
  ansible.builtin.import_playbook: ./containers_docker.playbook.yml

- name: Ansible for Automation
  ansible.builtin.import_playbook: ./automation_ansible.playbook.yml

- name: Neovim Text Editor
  ansible.builtin.import_playbook: ./editor_neovim.playbook.yml
