---
- name: Create bash plugins file
  become: true
  ansible.builtin.copy:
    content: ""
    dest: /usr/local/share/werkstatt/bash_plugins
    force: false
    mode: u=rw,go=r

- name: Add bash plugins
  become: true
  ansible.builtin.lineinfile:
    path: /usr/local/share/werkstatt/bash_plugins
    line: "{{ item }}"
  loop: "{{ bash_plugins_to_add }}"
