---
- name: Create bash plugins file
  become: true
  ansible.builtin.copy:
    content: ""
    dest: "{{ werkstatt_data_dir }}/bash_plugins"
    force: false
    mode: u=rw,go=r

- name: Add bash plugins
  become: true
  ansible.builtin.lineinfile:
    path: "{{ werkstatt_data_dir }}/bash_plugins"
    line: "{{ item }}"
  loop: "{{ bash_plugins_to_add }}"
