---
- name: Create bash paths file
  become: true
  ansible.builtin.copy:
    content: ""
    dest: "{{ werkstatt_data_dir }}/bash_paths"
    force: false
    mode: u=rw,go=r

- name: Add bash paths
  become: true
  ansible.builtin.lineinfile:
    path: "{{ werkstatt_data_dir }}/bash_paths"
    line: "{{ item }}"
  loop: "{{ bash_paths_to_add }}"
