---
- name: Create bash aliases file
  become: true
  ansible.builtin.copy:
    content: ""
    dest: "{{ werkstatt_data_dir }}/bash_aliases"
    force: false
    mode: u=rw,go=r

- name: Add bash aliases
  become: true
  loop: "{{ bash_aliases_to_add | dict2items }}"
  ansible.builtin.lineinfile:
    path: "{{ werkstatt_data_dir }}/bash_aliases"
    line: alias {{ item.key }}='{{ item.value }}'
##
# TODO add completion for aliases
#
# @see  {@link https://unix.stackexchange.com/a/685829/8245}
##
