---
- name: Create Fish configuration snippets directory
  ansible.builtin.file:
    path: ~/.config/fish/conf.d
    state: directory
    mode: u=rwX,g=rX,o=rX

- name: Add abbreviations
  loop: "{{ fish_abbreviations_to_add | dict2items }}"
  ansible.builtin.lineinfile:
    path: ~/.config/fish/conf.d/werkstatt_abbreviations.fish
    line: abbr --add {{ item.key }} '{{ item.value }}'
    create: yes
    mode: u=rw,g=r,o=r
