# THIS FILE IS MANAGED BY WERKSTATT.
# BECAUSE OF THE BLE.SH LINE EDITOR AND THE STARSHIP PROMPT.
# PLEASE CREATE ~/.bash_myrc FOR PERSONAL CUSTOMIZATIONS.
# THIS FILE WILL SOURCE ~/.bash_myrc.

#--- ble.sh Line Editor - First Step of Activation

# Werkstatt - line below must the first line of code.
 [[ $- == *i* ]] && source ~/.local/share/blesh/ble.sh --attach=none

#--- Globbing

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

#--- History

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it.
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1).
HISTSIZE=1000
HISTFILESIZE=2000

HISTTIMEFORMAT="%F %T "

#--- Terminal Window

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#--- Environment Variables

##------ Werkstatt Environment Variables

if [ -f /usr/local/share/werkstatt/bash_env ]; then
  . /usr/local/share/werkstatt/bash_env
fi

##------ Executable Path

# Paths supplied by Werkstatt.
if [ -f /usr/local/share/werkstatt/bash_paths ]; then
  for WERKSTATT_ADDITIONAL_PATH in $(cat /usr/local/share/werkstatt/bash_paths); do
    if [[ ! -z $WERKSTATT_ADDITIONAL_PATH ]]; then
      if [[ $PATH != *"$WERKSTATT_ADDITIONAL_PATH"* ]]; then
        export PATH=$WERKSTATT_ADDITIONAL_PATH:$PATH
      fi
    fi
  done
fi

#--- Plugins

if [ -f /usr/local/share/werkstatt/bash_plugins ]; then
  . /usr/local/share/werkstatt/bash_plugins
fi

#--- Aliases

##------ Werkstatt Aliases

if [ -f /usr/local/share/werkstatt/bash_aliases ]; then
  . /usr/local/share/werkstatt/bash_aliases
fi

##------ User Aliases

# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#--- Completions

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#--- Utility Programmes

##------ chroot

# Set variable identifying the chroot you work in (used in the prompt below).
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

##------ less

# Make less more friendly for non-text input files, see lesspipe(1).
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

##------ ls

# Enable color support of ls, dir, grep and variants.
if [ -x /usr/bin/dircolors ]; then
    # dircolors sets the LS_COLORS environment variable then exports it.
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

#--- User Configuration

# Write your bash customizations in the file below.
if [[ -f ~/.bash_myrc ]]; then
    . ~/.bash_myrc
fi

#--- Prompt

eval "$(starship init bash)"

#--- ble.sh Line Editor - Second Step of Activation

[[ ${BLE_VERSION-} ]] && ble-attach
# Werkstatt - above line must be the last line of code.
