# THIS FILE IS MANAGED BY WERKSTATT.
# PLEASE CREATE $HOME/.bash_myrc FOR PERSONAL CUSTOMIZATIONS.
# THIS FILE WILL SOURCE $HOME/.bash_myrc.

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

#--- Globbing

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

#--- History

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it.
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1).
HISTSIZE=1000
HISTFILESIZE=2000

HISTTIMEFORMAT="%F %T "

#--- Terminal Window

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#--- Environment Variables

##------ Werkstatt Environment Variables

if [[ -f /usr/local/share/werkstatt/bash_env ]]; then
	source /usr/local/share/werkstatt/bash_env
fi

##------ User Environment Variables

if [[ -f "$HOME/.bash_env" ]]; then
	source "$HOME/.bash_env"
fi

##------ Executable Path

###--------- Werkstatt Executble Paths

if [[ -f /usr/local/share/werkstatt/bash_paths ]]; then
	while IFS="" read -r WERKSTATT_ADDITIONAL_PATH || [[ -n "$WERKSTATT_ADDITIONAL_PATH" ]]; do
		if [[ -n "$WERKSTATT_ADDITIONAL_PATH" ]] && [[ -d "$WERKSTATT_ADDITIONAL_PATH" ]] && [[ $PATH != *"$WERKSTATT_ADDITIONAL_PATH"* ]]; then
			export PATH=$WERKSTATT_ADDITIONAL_PATH:$PATH
		fi
	done </usr/local/share/werkstatt/bash_paths
fi

###--------- User Executble Paths

if [[ -f "$HOME/.bash_paths" ]]; then
	while IFS="" read -r USER_ADDITIONAL_PATH || [[ -n "$USER_ADDITIONAL_PATH" ]]; do
		if [[ -n "$USER_ADDITIONAL_PATH" ]] && [[ -d "$USER_ADDITIONAL_PATH" ]] && [[ $PATH != *"$USER_ADDITIONAL_PATH"* ]]; then
			export PATH=$USER_ADDITIONAL_PATH:$PATH
		fi
	done <"$HOME/.bash_paths"
fi

#--- Plugins

if [[ -f /usr/local/share/werkstatt/bash_plugins ]]; then
	source /usr/local/share/werkstatt/bash_plugins
fi

#--- Aliases

##------ Werkstatt Aliases

if [[ -f /usr/local/share/werkstatt/bash_aliases ]]; then
	source /usr/local/share/werkstatt/bash_aliases
fi

##------ User Aliases

if [[ -f $HOME/.bash_aliases ]]; then
	source $HOME/.bash_aliases
fi

#--- Completions

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [[ -f /usr/share/bash-completion/bash_completion ]]; then
		source /usr/share/bash-completion/bash_completion
	elif [[ -f /etc/bash_completion ]]; then
		source /etc/bash_completion
	fi
fi

#--- Utility Programmes

##------ chroot

# Set variable identifying the chroot you work in (used in the prompt below).
if [[ -z "${debian_chroot:-}" ]] && [[ -r /etc/debian_chroot ]]; then
	debian_chroot=$(cat /etc/debian_chroot)
fi

##------ less

# Make less more friendly for non-text input files, see lesspipe(1).
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

##------ ls

# Enable color support of ls, dir, grep and variants.
if [[ -x /usr/bin/dircolors ]]; then
	# dircolors sets the LS_COLORS environment variable then exports it.
	test -r "$HOME/.dircolors" && eval "$(dircolors -b $HOME/.dircolors)" || eval "$(dircolors -b)"
fi

#--- User Configuration

# Write your bash customizations in the file below.
if [[ -f "$HOME/.bash_myrc" ]]; then
	source "$HOME/.bash_myrc"
fi

#--- Line Editing Mode

set -o vi

#--- Prompt

eval "$(starship init bash)"
