---
- name: Install and configure Ansible.
  hosts: factory
  vars:
    fish_path: /usr/bin/fish
  tasks:
    - name: Add abbreviations for Ansible.
      ansible.builtin.shell:
        executable: "{{ fish_path }}"
        cmd: abbr --add {{ item.word }} {{ item.expansion }}
      loop:
        - word: a
          expansion: ansible
        - word: ap
          expansion: ansible-playbook
        - word: agx
          expansion: ansible-galaxy

    - name: Install Ansible.
      vars:
        ansible_install_method: pip
      ansible.builtin.import_role:
        name: geerlingguy.ansible
      become: yes
