---
- name: Install and configure Ansible.
  hosts: factory

  vars:
    fish_path: /usr/bin/fish

    fish_ansible_abbreviations:
      a: ansible
      ap: ansible-playbook
      agx: ansible-galaxy
      mol: molecule

  tasks:
    # This is necessary when connecting to the managed node with an SSH password
    # that is used from the inventory file.
    - name: Enable noninteractive SSH password authentication
      become: yes
      ansible.builtin.apt:
        package: sshpass
        state: present

    - name: Collect existing abbreviations in a list.
      ansible.builtin.shell:
        executable: "{{ fish_path }}"
        cmd: abbr | cut --delimeter=' ' --fields=5
      register: fish_abbreviations
      changed_when: no

    - name: Find missing abbreviations.
      ansible.builtin.set_fact:
        fish_missing_abbreviations: "{{ fish_ansible_abbreviations.keys() | list | difference(fish_abbreviations.stdout.splitlines()) }}"

    - name: Add abbreviations for Ansible.
      when: fish_missing_abbreviations
      ansible.builtin.shell:
        executable: "{{ fish_path }}"
        cmd: abbr --add {{ item.key }} '{{ item.value }}'
      loop: "{{ fish_ansible_abbreviations | dict2items | selectattr('key', 'in', fish_missing_abbreviations) }}"

    - name: Install Ansible packages into the main Python virtual environment.
      ansible.builtin.shell:
        executable: "{{ fish_path }}"
        cmd: |
          vf activate main
          pip install {{ item }}
        creates: ~/.virtualenvs/main/bin/{{ item }}
      loop:
        - ansible
        - ansible-lint
        - molecule
