---
- name: Install Friendly Interactive Shell
  hosts: factory

  tasks:
    - name: Install Fish
      become: yes
      block:
        - name: Add Personal Package Archive
          ansible.builtin.apt_repository:
            repo: "ppa:fish-shell/release-3"
            state: present

        - name: Install Fish package
          ansible.builtin.apt:
            package: fish
            state: present

    - name: Default shell
      block:
        - name: Is Fish the default shell?
          ansible.builtin.shell:
            cmd: >
              cat /etc/passwd
              | grep $(whoami)
              | cut --delimiter=":" --fields=7
          register: fish_find_current_shell
          changed_when: no

        - name: Make Fish the default shell
          when: fish_find_current_shell.stdout != fish_path
          become: yes
          ansible.builtin.command:
            cmd: usermod --shell {{ fish_path }} {{ ansible_user }}

    - name: Path to fish command
      block:
        - name: Get path to fish command
          ansible.builtin.command:
            cmd: which fish
          register: fish_which_fish
          changed_when: no

        - name: Set path to fish command as fact
          ansible.builtin.set_fact:
            fish_path: fish_which_fish.stdout

    - name: Use Vi key bindings
      ansible.builtin.lineinfile:
        path: ~/.config/fish/config.fish
        mode: u=rw,g=r,o=r
        line: fish_vi_key_bindings
        state: present
        create: yes

    - name: Fisher - Package Manager for the Fish Shell
      block:
        - name: Download Fisher installer
          ansible.builtin.uri:
            url: https://git.io/fisher
            follow_redirects: yes
          register: fish_download_fisher_installer

        - name: Set Fisher install script as fact
          ansible.builtin.set_fact:
            fish_fisher_install_script: fish_download_fisher_installer.content

        - name: Install Fisher
          ansible.builtin.shell:
            executable: "{{ fish_path }}"
            cmd: >
              source {{ fish_fisher_install_script }}
              &&
              fisher install jorgebucaran/fisher
            creates: ~/.config/fish/functions/fisher.fish

    - name: Install Tide prompt
      ansible.builtin.shell:
        executable: "{{ fish_path }}"
        cmd: fisher install ilancosman/tide@v5
        creates: ~/.config/fish/functions/tide.fish

    - name: Configure Tide prompt
      ansible.builtin.shell:
        executable: "{{ fish_path }}"
        cmd: echo 1 1 3 2 2 1 2 2 y | tide configure >/dev/null
      changed_when: no

    - name: Add general abbreviations
      vars:
        fish_abbreviations_to_add:
          apt: sudo apt
          apti: sudo apt install
          aptu: sudo apt update
          aptug: sudo apt upgrade
          s: sudo service
      ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml

    - name: Add general aliases
      vars:
        fish_aliases_to_add:
          - name: history
            definition: 'history --show-time="%F %T "'
      ansible.builtin.include_tasks: ../tasks/fish_add_aliases.yml

    - name: Add local binary directory to $PATH
      vars:
        fish_directories_to_add:
          - /home/{{ ansible_user }}/.local/bin
      ansible.builtin.include_tasks: ../tasks/fish_add_directories_to_path.yml
