---
- name: Configure Git source code management
  hosts: factory
  tasks:
    - name: Add abbreviations for Git
      vars:
        fish_abbreviations_to_add:
          g: git
          gb: git branch
          gc: git commit
          gco: egit checkout
          gp: git push
          gpl: egit pull
          gr: git remote
          gs: git status
      ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml
