---
- name: Main
  hosts: all

  tasks:
    - name: Ensure packages are up-to-date
      become: yes
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ 60 * 60 * 24 * 7 }}" # 7 days in seconds
        upgrade: true

    - name: Install important general packages
      become: true
      ansible.builtin.apt:
        package:
          # build-essential contains list of packages necessary for building
          # Debian packages, such as C & C++ compilers. These are also
          # necessary for building other packages, e.g. Rust packages with
          # Cargo.
          - build-essential

- name: Werkstatt Development Environment
  ansible.builtin.import_playbook: ./werkstatt.yml

- name: Bash - Bourne Again Shell
  ansible.builtin.import_playbook: ./shell_bash.yml

- name: Rust Programming Language
  ansible.builtin.import_playbook: ./lang_rust.yml
  
- name: Go Programming Language
  ansible.builtin.import_playbook: ./lang_go.yml

# - name: Python Programming Language
#   ansible.builtin.import_playbook: ./lang_python.yml

- name: JavaScript Programming Language
  ansible.builtin.import_playbook: ./lang_javascript.yml

- name: Utility Programmes
  ansible.builtin.import_playbook: ./utils.yml

- name: Version Control with Git
  ansible.builtin.import_playbook: ./version_control_git.yml

# - name: Containerization with Docker
#   ansible.builtin.import_playbook: ./containers_docker.yml
#
# - name: Automation with Ansible
#   ansible.builtin.import_playbook: ./automation_ansible.yml

- name: Neovim Text Editor
  ansible.builtin.import_playbook: ./editor_neovim.yml
