# This file is part of Werkstatt.
#
# Werkstatt is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Werkstatt is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Werkstatt. If not, see <https://www.gnu.org/licenses/>.

##
# Ansible playbook that runs all the subsidiary playbooks in the correct
# sequence.
#
# This playbook should only be run in the target distribution (Fabrik) has
# already been prepared with the manual steps described in CONTRIBUTING and
# with the fabrik.yml playbook.
#
# @author     Geoffrey Bernardo van Wyk <geoffrey@vanwyk.biz>
# @copyright  2024 Geoffrey Bernardo van Wyk {@link https://geoffreyvanwyk.dev}
# @license    {@link http://www.gnu.org/copyleft/gpl.html} GNU GPL v3 or later
# @see        {@link https://starship.rs} Starship
###
---
- name: Main
  hosts: all

  tasks:
    - name: Ensure packages are up-to-date
      become: yes
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ 60 * 60 * 24 * 7 }}" # 7 days in seconds
        upgrade: true

    - name: Create XDG directories
      block:
        - name: Create $XDG_CONFIG_HOME
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.config"
            state: directory
            mode: u=rwX,go=rX

        - name: Create $XDG_DATA_HOME
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/.local/share"
            state: directory
            mode: u=rwX,go=rX

    - name: Create Werkstatt resource directory
      become: true
      ansible.builtin.file:
        path: /usr/local/share/werkstatt
        state: directory
        mode: u=rwX,go=rX

- name: Starship - minimal, blazingly fast, infinitely customizable prompt
  ansible.builtin.import_playbook: ./shellprompt_starship.yml

- name: Bash - Bourne Again Shell
  ansible.builtin.import_playbook: ./shell_bash.yml

- name: Python Programming Language
  ansible.builtin.import_playbook: ./lang_python.yml
# - name: Rust Programming Language
#   ansible.builtin.import_playbook: ./lang_rust.yml
#
# - name: Go Programming Language
#   ansible.builtin.import_playbook: ./lang_go.yml

# - name: JavaScript Programming Language
#   ansible.builtin.import_playbook: ./lang_javascript.yml
#
# - name: Utility Programmes
#   ansible.builtin.import_playbook: ./utils.yml
#
# - name: Version Control with Git
#   ansible.builtin.import_playbook: ./version_control_git.yml

# - name: Containerization with Docker
#   ansible.builtin.import_playbook: ./containers_docker.yml
#
# - name: Automation with Ansible
#   ansible.builtin.import_playbook: ./automation_ansible.yml

# - name: Neovim Text Editor
#   ansible.builtin.import_playbook: ./editor_neovim.yml
