---
- name: Provision Werkstatt development environment
  hosts: factory
  tasks:
    - name: Ensure packages are up-to-date
      become: yes
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ 3600 * 24 * 7 }}" # 7 days
        upgrade: true

- name: Install Friendly Interactive Shell
  ansible.builtin.import_playbook: ./fish.yml

- name: Install utility commands
  ansible.builtin.import_playbook: ./utils.yml

- name: Configure Git source code management
  ansible.builtin.import_playbook: ./git.yml

- name: Install Python packages and virtual environments
  ansible.builtin.import_playbook: ./python.yml

- name: Install and configure Ansible
  ansible.builtin.import_playbook: ./ansible.yml

- name: Install Docker containerization system
  ansible.builtin.import_playbook: ./docker.yml
