---
- name: Install Python packages and virtual environments.
  hosts: factory
  tasks:
    - name: Create symbolic link for python command
      become: yes
      ansible.builtin.file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - name: Install pip - Python package manager.
      ansible.builtin.import_role:
        name: geerlingguy.pip
      become: yes

    - name: VirtualFish - Python virtual environment manager for the Fish Shell
      block:
        - name: Install VirtualFish installer
          ansible.builtin.pip:
            name: virtualfish

        - name: Create directory for virtual environments
          ansible.builtin.file:
            path: ~/.virtualenvs
            state: directory
            mode: 0775

        - name: Install VirtualFish
          ansible.builtin.shell:
            executable: "{{ werkstatt_fish_path }}"
            cmd: vf install
          register: python_install_virtualfish
          changed_when: "'VirtualFish is already installed!' not in python_install_virtualfish.stdout"

    - name: Main virtual environment
      block:
        - name: Create main virtual environment
          ansible.builtin.shell:
            executable: "{{ werkstatt_fish_path }}"
            cmd: vf new main
            creates: ~/.virtualenvs/main

        - name: Activate main virtual environment when logging in
          ansible.builtin.lineinfile:
            path: ~/.config/fish/config.fish
            line: vf activate main
            state: present
            create: yes
            mode: 0664

    - name: Add aliases for Python
      vars:
        fish_aliases_to_add:
          - name: py
            definition: python
      ansible.builtin.include_tasks: ../tasks/fish_add_aliases.yml
