---
- name: Bash - Bourne Again Shell
  hosts: all

  tasks:
    - name: Add bash environment variables
      vars:
        bash_envs_to_add:
          XDG_CONFIG_HOME: $HOME/.config
      ansible.builtin.include_tasks: ../tasks/bash_add_env.yml

    - name: Add bash aliases
      vars:
        bash_aliases_to_add:
          dir: dir --color=auto
          vdir: vdir --color=auto
          grep: grep --color=auto
          fgrep: fgrep --color=auto
          egrep: egrep --color=auto
      ansible.builtin.include_tasks: ../tasks/bash_add_aliases.yml

      # This file is for the user to copy in case he messes up ~/.bashrc.
    - name: Deploy bash run-commands # noqa no-relative-paths
      become: true
      ansible.builtin.copy:
        src: ../files/bashrc
        dest: /usr/local/share/werkstatt/bashrc
        mode: u=rw,go=r

    - name: Deploy bash run-commands file for user # noqa no-relative-paths
      ansible.builtin.copy:
        src: ../files/bashrc
        dest: "{{ ansible_env.HOME }}/.bashrc"
        mode: u=rw,go=r

- name: Starship - minimal, blazingly fast, infinitely customizable prompt
  hosts: all

  tasks:
    - name: Is Starship installed?
      ansible.builtin.stat:
        path: /usr/local/bin/starship
      register: werkstatt_stat_starship

    - name: Download and install Starship
      when: not werkstatt_stat_starship.stat.exists
      block:
        - name: Download Starship installation script
          ansible.builtin.get_url:
            url: https://starship.rs/install.sh
            dest: /tmp/starship_install.sh
            mode: ugo=rwx

        - name: Install Starship
          become: true
          ansible.builtin.shell:
            executable: /usr/bin/bash
            chdir: /tmp
            cmd: ./starship_install.sh --yes
            creates: /usr/local/bin/starship

    - name: Delete Starship install script
      ansible.builtin.file:
        path: /tmp/starship_install.sh
        state: absent
