# This file is part of Werkstatt.
#
# Werkstatt is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Werkstatt is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Werkstatt. If not, see <https://www.gnu.org/licenses/>.

##
# Ansible playbook that configures the bash shell.
#
# @see        {@link https://www.gnu.org/software/bash/} Bash - GNU Project - Free Software Foundation
# @author     Geoffrey Bernardo van Wyk <geoffrey@vanwyk.biz>
# @copyright  2024 Geoffrey Bernardo van Wyk {@link https://geoffreyvanwyk.dev}
# @license    {@link http://www.gnu.org/copyleft/gpl.html} GNU GPL v3 or later
##
---
- name: BASH - Bourne Again Shell
  hosts: all

  tasks:
    - name: Add bash environment variables
      vars:
        bash_envs_to_add:
          XDG_BIN_HOME: "{{ werkstatt_xdg_bin_home }}"
          XDG_CACHE_HOME: "{{ werkstatt_xdg_cache_home }}"
          XDG_CONFIG_HOME: "{{ werkstatt_xdg_config_home }}"
          XDG_DATA_HOME: "{{ werkstatt_xdg_data_home }}"
          XDG_STATE_HOME: "{{ werkstatt_xdg_state_home }}"
      ansible.builtin.include_tasks: ../tasks/bash_add_env.yml

    - name: Add directory paths to bash $PATH
      vars:
        bash_paths_to_add:
          - "{{ werkstatt_xdg_bin_home }}"
      ansible.builtin.include_tasks: ../tasks/bash_add_paths.yml

    - name: Add bash aliases
      vars:
        bash_aliases_to_add:
          a: sudo apt
          dir: dir --color=auto
          egrep: egrep --color=auto
          fgrep: fgrep --color=auto
          grep: grep --color=auto
          ls: ls --color=auto
          s: sudo service
          vdir: vdir --color=auto
      ansible.builtin.include_tasks: ../tasks/bash_add_aliases.yml

    - name: Create bash completions directory
      ansible.builtin.file:
        path: "{{ werkstatt_xdg_data_home }}/bash-completion/completions"
        state: directory
        mode: u=rwX,go=rX

      # This file is for the user to copy in case he messes up ~/.bashrc.
    - name: Deploy bash run-commands file # noqa no-relative-paths
      ansible.builtin.copy:
        src: ../files/bashrc
        dest: "{{ werkstatt_data_dir }}/bashrc"
        mode: u=rw,go=r

    - name: Deploy bash run-commands file for user # noqa no-relative-paths
      ansible.builtin.copy:
        src: ../files/bashrc
        dest: "{{ ansible_env.HOME }}/.bashrc"
        mode: u=rw,go=r

      # This file is for the user to copy in case he messes up ~/.inputrc.
    - name: Deploy GNU Readline run-commands file # noqa no-relative-paths
      become: true
      ansible.builtin.copy:
        src: ../files/inputrc
        dest: "{{ werkstatt_data_dir }}/inputrc"
        mode: u=rw,go=r

    - name: Deploy GNU Readline run-commands file for user # noqa no-relative-paths
      ansible.builtin.copy:
        src: ../files/inputrc
        dest: "{{ ansible_env.HOME }}/.inputrc"
        mode: u=rw,go=r
