---
- name: Install utility commands
  hosts: all
  tasks:
    - name: Set path to fish command as fact
      ansible.builtin.include_tasks: ../tasks/fish_executable_path.yml

    - name: Install z directory jumper
      ansible.builtin.shell:
        executable: "{{ werkstatt_fish_path }}"
        cmd: fisher install jethrokuan/z
        creates: ~/.config/fish/functions/__z.fish

    # Dependency for fzf.fish
    - name: Fuzzy Finder
      block:
        - name: Clone repository of Fuzzy Finder
          ansible.builtin.git:
            repo: https://github.com/junegunn/fzf.git
            version: master
            dest: ~/.fzf

        - name: Install Fuzzy Finder # noqa risky-shell-pipe
          ansible.builtin.shell:
            executable: "{{ werkstatt_fish_path }}"
            chdir: ~/.fzf
            cmd: echo y | ./install
            creates: ~/.fzf/bin/fzf

    # Dependency for fzf.fish
    - name: Install fd - a superior find command
      become: yes
      ansible.builtin.apt:
        deb: https://github.com/sharkdp/fd/releases/download/v8.4.0/fd-musl_8.4.0_amd64.deb

    # Dependency for fzf.fish
    - name: Install bat - a superior cat
      become: yes
      ansible.builtin.apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_amd64.deb

    - name: Add abbreviations for bat
      vars:
        fish_abbreviations_to_add:
          cat: bat
      ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml

    - name: Install ef-fish-ient key bindings for Fuzzy Finder
      ansible.builtin.shell:
        executable: "{{ werkstatt_fish_path }}"
        cmd: fisher install PatrickF1/fzf.fish
        creates: ~/.config/fish/functions/_fzf_wrapper.fish

    # Homepage: https://the.exa.website
    - name: Install exa - a modern replacement for ls.
      become: yes
      ansible.builtin.apt:
        package: exa

    - name: Add abbreviations for exa
      vars:
        fish_abbreviations_to_add:
          ls: exa
          l: exa --classify --grid
          la: exa --all
          ll: exa --all --classify --long
          lt: exa --all --long --tree
      ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml

    # Many use cases, e.g. used by Phoenix web framework for live reloading of
    # web pages when code changes.
    - name: Install Inotify Tools - A file watcher
      become: yes
      ansible.builtin.apt:
        package:
          - inotify-tools
