---
- name: Utility programmes
  hosts: all

  tasks:
    # Dependency for fzf.fish
    - name: Bat - a superior cat
      block:
        - name: Install bat
          become: yes
          ansible.builtin.apt:
            deb: https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_amd64.deb

        - name: Add abbreviations for bat
          vars:
            fish_abbreviations_to_add:
              cat: bat
          ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml

    - name: Z - a directory jumper
      ansible.builtin.command:
        cmd: fisher install jethrokuan/z
        creates: ~/.config/fish/functions/__z.fish

    # Dependency for fzf.fish
    - name: FD - a superior find command
      become: yes
      ansible.builtin.apt:
        deb: https://github.com/sharkdp/fd/releases/download/v8.4.0/fd-musl_8.4.0_amd64.deb

    # Dependency for fzf.fish
    - name: FZF - a fuzzy finder
      block:
        - name: Clone repository of Fuzzy Finder
          ansible.builtin.git:
            repo: https://github.com/junegunn/fzf.git
            dest: ~/.fzf
            version: master
            update: false

        - name: Install Fuzzy Finder
          ansible.builtin.shell:
            executable: /usr/bin/bash
            chdir: ~/.fzf
            cmd: set -o pipefail && echo y | ./install
            creates: ~/.fzf/bin/fzf

        - name: Install ef-fish-ient key bindings for Fuzzy Finder
          ansible.builtin.command:
            cmd: fisher install PatrickF1/fzf.fish
            creates: ~/.config/fish/functions/_fzf_wrapper.fish

    # Homepage: https://the.exa.website
    - name: Exa - a modern replacement for ls
      block:
        - name: Install exa
          become: yes
          ansible.builtin.apt:
            package: exa

        - name: Add abbreviations for exa
          vars:
            fish_abbreviations_to_add:
              ls: exa
              l: exa --classify --grid
              la: exa --all
              ll: exa --all --classify --long
              lt: exa --all --long --tree
          ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml

    - name: RipGrep - a faster grep
      block:
        - name: Create directory for ripgrep source code
          become: true
          ansible.builtin.file:
            path: /opt/ripgrep
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: u=rwX,go=rX

        - name: Clone ripgrep source code repository
          ansible.builtin.git:
            repo: https://github.com/BurntSushi/ripgrep
            dest: /opt/ripgrep
            version: 14.1.0
          notify: Compile then install ripgrep

    # Run with command: btm
    - name: Bottom - a superior top
      become: true
      vars:
        werkstatt_bottom_version: 0.9.6
      ansible.builtin.apt:
        deb: https://github.com/ClementTsang/bottom/releases/download/{{ werkstatt_bottom_version }}/bottom_{{ werkstatt_bottom_version }}_amd64.deb

- name: GDU - A faster du, with terminal UI
  hosts: all

  vars:
    werkstatt_gdu_version: v5.27.0

  tasks:
    - name: Is gdu already installed?
      ansible.builtin.stat:
        path: /usr/local/bin/gdu
      register: werkstatt_stat_gdu

    - name: Display current gdu version
      when: werkstatt_stat_gdu.stat.exists
      ansible.builtin.shell:
        executable: /usr/bin/bash
        cmd: set -o pipefail && gdu --version | head -n1 | sed 's/Version:\s\+//'
      changed_when: false
      register: werkstatt_display_current_gdu_version

    - name: Is gdu version outdated?
      ansible.builtin.set_fact:
        werkstatt_is_gdu_outdated: "{{
          not werkstatt_stat_gdu.stat.exists
          or
          not (werkstatt_display_current_gdu_version.stdout == werkstatt_gdu_version) }}"

    - name: Download, extract, then install gdu
      when: werkstatt_is_gdu_outdated
      block:
        - name: Download gdu archive
          ansible.builtin.get_url:
            url: https://github.com/dundee/gdu/releases/download/{{ werkstatt_gdu_version }}/gdu_linux_amd64.tgz
            dest: /home/{{ ansible_user }}/gdu_linux_amd64.tgz
            mode: u=rw,go=r

        - name: Extract gdu archive
          ansible.builtin.unarchive:
            src: /home/{{ ansible_user }}/gdu_linux_amd64.tgz
            remote_src: true
            dest: /home/{{ ansible_user }}

        - name: Install gdu archive
          become: true
          ansible.builtin.copy:
            src: /home/{{ ansible_user }}/gdu_linux_amd64
            remote_src: true
            dest: /usr/local/bin/gdu
            mode: u=rwx,go=rx

    - name: Delete gdu archive
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/gdu_linux_amd64.tgz
        state: absent

    - name: Delete gdu extracted file
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/gdu_linux_amd64
        state: absent
