---
- name: Werkstatt Development Environment
  hosts: all

  tasks:
    - name: Create Werkstatt configuration directory
      become: true
      ansible.builtin.file:
        path: /usr/local/share/werkstatt
        state: directory
        mode: u=rwX,go=rX
